// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Implant is the predicate function for implant builders.
type Implant func(*sql.Selector)
