// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"github.com/bishopfox/sliver/server/db/ent/buildtask"
	"github.com/bishopfox/sliver/server/db/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// BuildTaskQuery is the builder for querying BuildTask entities.
type BuildTaskQuery struct {
	config
	limit      *int
	offset     *int
	order      []OrderFunc
	unique     []string
	predicates []predicate.BuildTask
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the builder.
func (btq *BuildTaskQuery) Where(ps ...predicate.BuildTask) *BuildTaskQuery {
	btq.predicates = append(btq.predicates, ps...)
	return btq
}

// Limit adds a limit step to the query.
func (btq *BuildTaskQuery) Limit(limit int) *BuildTaskQuery {
	btq.limit = &limit
	return btq
}

// Offset adds an offset step to the query.
func (btq *BuildTaskQuery) Offset(offset int) *BuildTaskQuery {
	btq.offset = &offset
	return btq
}

// Order adds an order step to the query.
func (btq *BuildTaskQuery) Order(o ...OrderFunc) *BuildTaskQuery {
	btq.order = append(btq.order, o...)
	return btq
}

// First returns the first BuildTask entity in the query. Returns *NotFoundError when no buildtask was found.
func (btq *BuildTaskQuery) First(ctx context.Context) (*BuildTask, error) {
	bts, err := btq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(bts) == 0 {
		return nil, &NotFoundError{buildtask.Label}
	}
	return bts[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (btq *BuildTaskQuery) FirstX(ctx context.Context) *BuildTask {
	bt, err := btq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return bt
}

// FirstID returns the first BuildTask id in the query. Returns *NotFoundError when no id was found.
func (btq *BuildTaskQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = btq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{buildtask.Label}
		return
	}
	return ids[0], nil
}

// FirstXID is like FirstID, but panics if an error occurs.
func (btq *BuildTaskQuery) FirstXID(ctx context.Context) int {
	id, err := btq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns the only BuildTask entity in the query, returns an error if not exactly one entity was returned.
func (btq *BuildTaskQuery) Only(ctx context.Context) (*BuildTask, error) {
	bts, err := btq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(bts) {
	case 1:
		return bts[0], nil
	case 0:
		return nil, &NotFoundError{buildtask.Label}
	default:
		return nil, &NotSingularError{buildtask.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (btq *BuildTaskQuery) OnlyX(ctx context.Context) *BuildTask {
	bt, err := btq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return bt
}

// OnlyID returns the only BuildTask id in the query, returns an error if not exactly one id was returned.
func (btq *BuildTaskQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = btq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{buildtask.Label}
	default:
		err = &NotSingularError{buildtask.Label}
	}
	return
}

// OnlyXID is like OnlyID, but panics if an error occurs.
func (btq *BuildTaskQuery) OnlyXID(ctx context.Context) int {
	id, err := btq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of BuildTasks.
func (btq *BuildTaskQuery) All(ctx context.Context) ([]*BuildTask, error) {
	if err := btq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return btq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (btq *BuildTaskQuery) AllX(ctx context.Context) []*BuildTask {
	bts, err := btq.All(ctx)
	if err != nil {
		panic(err)
	}
	return bts
}

// IDs executes the query and returns a list of BuildTask ids.
func (btq *BuildTaskQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := btq.Select(buildtask.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (btq *BuildTaskQuery) IDsX(ctx context.Context) []int {
	ids, err := btq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (btq *BuildTaskQuery) Count(ctx context.Context) (int, error) {
	if err := btq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return btq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (btq *BuildTaskQuery) CountX(ctx context.Context) int {
	count, err := btq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (btq *BuildTaskQuery) Exist(ctx context.Context) (bool, error) {
	if err := btq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return btq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (btq *BuildTaskQuery) ExistX(ctx context.Context) bool {
	exist, err := btq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the query builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (btq *BuildTaskQuery) Clone() *BuildTaskQuery {
	return &BuildTaskQuery{
		config:     btq.config,
		limit:      btq.limit,
		offset:     btq.offset,
		order:      append([]OrderFunc{}, btq.order...),
		unique:     append([]string{}, btq.unique...),
		predicates: append([]predicate.BuildTask{}, btq.predicates...),
		// clone intermediate query.
		sql:  btq.sql.Clone(),
		path: btq.path,
	}
}

// GroupBy used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		GUID uuid.UUID `json:"guid,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.BuildTask.Query().
//		GroupBy(buildtask.FieldGUID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (btq *BuildTaskQuery) GroupBy(field string, fields ...string) *BuildTaskGroupBy {
	group := &BuildTaskGroupBy{config: btq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := btq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return btq.sqlQuery(), nil
	}
	return group
}

// Select one or more fields from the given query.
//
// Example:
//
//	var v []struct {
//		GUID uuid.UUID `json:"guid,omitempty"`
//	}
//
//	client.BuildTask.Query().
//		Select(buildtask.FieldGUID).
//		Scan(ctx, &v)
//
func (btq *BuildTaskQuery) Select(field string, fields ...string) *BuildTaskSelect {
	selector := &BuildTaskSelect{config: btq.config}
	selector.fields = append([]string{field}, fields...)
	selector.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := btq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return btq.sqlQuery(), nil
	}
	return selector
}

func (btq *BuildTaskQuery) prepareQuery(ctx context.Context) error {
	if btq.path != nil {
		prev, err := btq.path(ctx)
		if err != nil {
			return err
		}
		btq.sql = prev
	}
	return nil
}

func (btq *BuildTaskQuery) sqlAll(ctx context.Context) ([]*BuildTask, error) {
	var (
		nodes = []*BuildTask{}
		_spec = btq.querySpec()
	)
	_spec.ScanValues = func() []interface{} {
		node := &BuildTask{config: btq.config}
		nodes = append(nodes, node)
		values := node.scanValues()
		return values
	}
	_spec.Assign = func(values ...interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(values...)
	}
	if err := sqlgraph.QueryNodes(ctx, btq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (btq *BuildTaskQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := btq.querySpec()
	return sqlgraph.CountNodes(ctx, btq.driver, _spec)
}

func (btq *BuildTaskQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := btq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %v", err)
	}
	return n > 0, nil
}

func (btq *BuildTaskQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   buildtask.Table,
			Columns: buildtask.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: buildtask.FieldID,
			},
		},
		From:   btq.sql,
		Unique: true,
	}
	if ps := btq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := btq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := btq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := btq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (btq *BuildTaskQuery) sqlQuery() *sql.Selector {
	builder := sql.Dialect(btq.driver.Dialect())
	t1 := builder.Table(buildtask.Table)
	selector := builder.Select(t1.Columns(buildtask.Columns...)...).From(t1)
	if btq.sql != nil {
		selector = btq.sql
		selector.Select(selector.Columns(buildtask.Columns...)...)
	}
	for _, p := range btq.predicates {
		p(selector)
	}
	for _, p := range btq.order {
		p(selector)
	}
	if offset := btq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := btq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BuildTaskGroupBy is the builder for group-by BuildTask entities.
type BuildTaskGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (btgb *BuildTaskGroupBy) Aggregate(fns ...AggregateFunc) *BuildTaskGroupBy {
	btgb.fns = append(btgb.fns, fns...)
	return btgb
}

// Scan applies the group-by query and scan the result into the given value.
func (btgb *BuildTaskGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := btgb.path(ctx)
	if err != nil {
		return err
	}
	btgb.sql = query
	return btgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (btgb *BuildTaskGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := btgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by. It is only allowed when querying group-by with one field.
func (btgb *BuildTaskGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(btgb.fields) > 1 {
		return nil, errors.New("ent: BuildTaskGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := btgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (btgb *BuildTaskGroupBy) StringsX(ctx context.Context) []string {
	v, err := btgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by. It is only allowed when querying group-by with one field.
func (btgb *BuildTaskGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(btgb.fields) > 1 {
		return nil, errors.New("ent: BuildTaskGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := btgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (btgb *BuildTaskGroupBy) IntsX(ctx context.Context) []int {
	v, err := btgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by. It is only allowed when querying group-by with one field.
func (btgb *BuildTaskGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(btgb.fields) > 1 {
		return nil, errors.New("ent: BuildTaskGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := btgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (btgb *BuildTaskGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := btgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by. It is only allowed when querying group-by with one field.
func (btgb *BuildTaskGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(btgb.fields) > 1 {
		return nil, errors.New("ent: BuildTaskGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := btgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (btgb *BuildTaskGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := btgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (btgb *BuildTaskGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := btgb.sqlQuery().Query()
	if err := btgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (btgb *BuildTaskGroupBy) sqlQuery() *sql.Selector {
	selector := btgb.sql
	columns := make([]string, 0, len(btgb.fields)+len(btgb.fns))
	columns = append(columns, btgb.fields...)
	for _, fn := range btgb.fns {
		columns = append(columns, fn(selector))
	}
	return selector.Select(columns...).GroupBy(btgb.fields...)
}

// BuildTaskSelect is the builder for select fields of BuildTask entities.
type BuildTaskSelect struct {
	config
	fields []string
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Scan applies the selector query and scan the result into the given value.
func (bts *BuildTaskSelect) Scan(ctx context.Context, v interface{}) error {
	query, err := bts.path(ctx)
	if err != nil {
		return err
	}
	bts.sql = query
	return bts.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (bts *BuildTaskSelect) ScanX(ctx context.Context, v interface{}) {
	if err := bts.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from selector. It is only allowed when selecting one field.
func (bts *BuildTaskSelect) Strings(ctx context.Context) ([]string, error) {
	if len(bts.fields) > 1 {
		return nil, errors.New("ent: BuildTaskSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := bts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (bts *BuildTaskSelect) StringsX(ctx context.Context) []string {
	v, err := bts.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from selector. It is only allowed when selecting one field.
func (bts *BuildTaskSelect) Ints(ctx context.Context) ([]int, error) {
	if len(bts.fields) > 1 {
		return nil, errors.New("ent: BuildTaskSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := bts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (bts *BuildTaskSelect) IntsX(ctx context.Context) []int {
	v, err := bts.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from selector. It is only allowed when selecting one field.
func (bts *BuildTaskSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(bts.fields) > 1 {
		return nil, errors.New("ent: BuildTaskSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := bts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (bts *BuildTaskSelect) Float64sX(ctx context.Context) []float64 {
	v, err := bts.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from selector. It is only allowed when selecting one field.
func (bts *BuildTaskSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(bts.fields) > 1 {
		return nil, errors.New("ent: BuildTaskSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := bts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (bts *BuildTaskSelect) BoolsX(ctx context.Context) []bool {
	v, err := bts.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (bts *BuildTaskSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := bts.sqlQuery().Query()
	if err := bts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (bts *BuildTaskSelect) sqlQuery() sql.Querier {
	selector := bts.sql
	selector.Select(selector.Columns(bts.fields...)...)
	return selector
}
