// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/bishopfox/sliver/server/db/ent/buildtask"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/google/uuid"
)

// BuildTaskCreate is the builder for creating a BuildTask entity.
type BuildTaskCreate struct {
	config
	mutation *BuildTaskMutation
	hooks    []Hook
}

// SetGUID sets the guid field.
func (btc *BuildTaskCreate) SetGUID(u uuid.UUID) *BuildTaskCreate {
	btc.mutation.SetGUID(u)
	return btc
}

// Mutation returns the BuildTaskMutation object of the builder.
func (btc *BuildTaskCreate) Mutation() *BuildTaskMutation {
	return btc.mutation
}

// Save creates the BuildTask in the database.
func (btc *BuildTaskCreate) Save(ctx context.Context) (*BuildTask, error) {
	if _, ok := btc.mutation.GUID(); !ok {
		return nil, &ValidationError{Name: "guid", err: errors.New("ent: missing required field \"guid\"")}
	}
	var (
		err  error
		node *BuildTask
	)
	if len(btc.hooks) == 0 {
		node, err = btc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BuildTaskMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			btc.mutation = mutation
			node, err = btc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(btc.hooks) - 1; i >= 0; i-- {
			mut = btc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, btc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (btc *BuildTaskCreate) SaveX(ctx context.Context) *BuildTask {
	v, err := btc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (btc *BuildTaskCreate) sqlSave(ctx context.Context) (*BuildTask, error) {
	var (
		bt    = &BuildTask{config: btc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: buildtask.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: buildtask.FieldID,
			},
		}
	)
	if value, ok := btc.mutation.GUID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: buildtask.FieldGUID,
		})
		bt.GUID = value
	}
	if err := sqlgraph.CreateNode(ctx, btc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	bt.ID = int(id)
	return bt, nil
}
