// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/bishopfox/sliver/server/db/ent/buildtask"
	"github.com/bishopfox/sliver/server/db/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// BuildTaskDelete is the builder for deleting a BuildTask entity.
type BuildTaskDelete struct {
	config
	hooks      []Hook
	mutation   *BuildTaskMutation
	predicates []predicate.BuildTask
}

// Where adds a new predicate to the delete builder.
func (btd *BuildTaskDelete) Where(ps ...predicate.BuildTask) *BuildTaskDelete {
	btd.predicates = append(btd.predicates, ps...)
	return btd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (btd *BuildTaskDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(btd.hooks) == 0 {
		affected, err = btd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BuildTaskMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			btd.mutation = mutation
			affected, err = btd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(btd.hooks) - 1; i >= 0; i-- {
			mut = btd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, btd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (btd *BuildTaskDelete) ExecX(ctx context.Context) int {
	n, err := btd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (btd *BuildTaskDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: buildtask.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: buildtask.FieldID,
			},
		},
	}
	if ps := btd.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, btd.driver, _spec)
}

// BuildTaskDeleteOne is the builder for deleting a single BuildTask entity.
type BuildTaskDeleteOne struct {
	btd *BuildTaskDelete
}

// Exec executes the deletion query.
func (btdo *BuildTaskDeleteOne) Exec(ctx context.Context) error {
	n, err := btdo.btd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{buildtask.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (btdo *BuildTaskDeleteOne) ExecX(ctx context.Context) {
	btdo.btd.ExecX(ctx)
}
