// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/bishopfox/sliver/server/db/ent/implantprofile"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// ImplantProfileCreate is the builder for creating a ImplantProfile entity.
type ImplantProfileCreate struct {
	config
	mutation *ImplantProfileMutation
	hooks    []Hook
}

// Mutation returns the ImplantProfileMutation object of the builder.
func (ipc *ImplantProfileCreate) Mutation() *ImplantProfileMutation {
	return ipc.mutation
}

// Save creates the ImplantProfile in the database.
func (ipc *ImplantProfileCreate) Save(ctx context.Context) (*ImplantProfile, error) {
	var (
		err  error
		node *ImplantProfile
	)
	if len(ipc.hooks) == 0 {
		node, err = ipc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ImplantProfileMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ipc.mutation = mutation
			node, err = ipc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ipc.hooks) - 1; i >= 0; i-- {
			mut = ipc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ipc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ipc *ImplantProfileCreate) SaveX(ctx context.Context) *ImplantProfile {
	v, err := ipc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ipc *ImplantProfileCreate) sqlSave(ctx context.Context) (*ImplantProfile, error) {
	var (
		ip    = &ImplantProfile{config: ipc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: implantprofile.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: implantprofile.FieldID,
			},
		}
	)
	if err := sqlgraph.CreateNode(ctx, ipc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	ip.ID = int(id)
	return ip, nil
}
