// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/bishopfox/sliver/server/db/ent/implantconfig"
	"github.com/facebookincubator/ent/dialect/sql"
)

// ImplantConfig is the model entity for the ImplantConfig schema.
type ImplantConfig struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ImplantConfig) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{}, // id
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ImplantConfig fields.
func (ic *ImplantConfig) assignValues(values ...interface{}) error {
	if m, n := len(values), len(implantconfig.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	ic.ID = int(value.Int64)
	values = values[1:]
	return nil
}

// Update returns a builder for updating this ImplantConfig.
// Note that, you need to call ImplantConfig.Unwrap() before calling this method, if this ImplantConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (ic *ImplantConfig) Update() *ImplantConfigUpdateOne {
	return (&ImplantConfigClient{config: ic.config}).UpdateOne(ic)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (ic *ImplantConfig) Unwrap() *ImplantConfig {
	tx, ok := ic.config.driver.(*txDriver)
	if !ok {
		panic("ent: ImplantConfig is not a transactional entity")
	}
	ic.config.driver = tx.drv
	return ic
}

// String implements the fmt.Stringer.
func (ic *ImplantConfig) String() string {
	var builder strings.Builder
	builder.WriteString("ImplantConfig(")
	builder.WriteString(fmt.Sprintf("id=%v", ic.ID))
	builder.WriteByte(')')
	return builder.String()
}

// ImplantConfigs is a parsable slice of ImplantConfig.
type ImplantConfigs []*ImplantConfig

func (ic ImplantConfigs) config(cfg config) {
	for _i := range ic {
		ic[_i].config = cfg
	}
}
