// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"github.com/bishopfox/sliver/server/db/ent/implantprofile"
	"github.com/bishopfox/sliver/server/db/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// ImplantProfileQuery is the builder for querying ImplantProfile entities.
type ImplantProfileQuery struct {
	config
	limit      *int
	offset     *int
	order      []OrderFunc
	unique     []string
	predicates []predicate.ImplantProfile
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the builder.
func (ipq *ImplantProfileQuery) Where(ps ...predicate.ImplantProfile) *ImplantProfileQuery {
	ipq.predicates = append(ipq.predicates, ps...)
	return ipq
}

// Limit adds a limit step to the query.
func (ipq *ImplantProfileQuery) Limit(limit int) *ImplantProfileQuery {
	ipq.limit = &limit
	return ipq
}

// Offset adds an offset step to the query.
func (ipq *ImplantProfileQuery) Offset(offset int) *ImplantProfileQuery {
	ipq.offset = &offset
	return ipq
}

// Order adds an order step to the query.
func (ipq *ImplantProfileQuery) Order(o ...OrderFunc) *ImplantProfileQuery {
	ipq.order = append(ipq.order, o...)
	return ipq
}

// First returns the first ImplantProfile entity in the query. Returns *NotFoundError when no implantprofile was found.
func (ipq *ImplantProfileQuery) First(ctx context.Context) (*ImplantProfile, error) {
	ips, err := ipq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(ips) == 0 {
		return nil, &NotFoundError{implantprofile.Label}
	}
	return ips[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ipq *ImplantProfileQuery) FirstX(ctx context.Context) *ImplantProfile {
	ip, err := ipq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return ip
}

// FirstID returns the first ImplantProfile id in the query. Returns *NotFoundError when no id was found.
func (ipq *ImplantProfileQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ipq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{implantprofile.Label}
		return
	}
	return ids[0], nil
}

// FirstXID is like FirstID, but panics if an error occurs.
func (ipq *ImplantProfileQuery) FirstXID(ctx context.Context) int {
	id, err := ipq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns the only ImplantProfile entity in the query, returns an error if not exactly one entity was returned.
func (ipq *ImplantProfileQuery) Only(ctx context.Context) (*ImplantProfile, error) {
	ips, err := ipq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(ips) {
	case 1:
		return ips[0], nil
	case 0:
		return nil, &NotFoundError{implantprofile.Label}
	default:
		return nil, &NotSingularError{implantprofile.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ipq *ImplantProfileQuery) OnlyX(ctx context.Context) *ImplantProfile {
	ip, err := ipq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return ip
}

// OnlyID returns the only ImplantProfile id in the query, returns an error if not exactly one id was returned.
func (ipq *ImplantProfileQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ipq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{implantprofile.Label}
	default:
		err = &NotSingularError{implantprofile.Label}
	}
	return
}

// OnlyXID is like OnlyID, but panics if an error occurs.
func (ipq *ImplantProfileQuery) OnlyXID(ctx context.Context) int {
	id, err := ipq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ImplantProfiles.
func (ipq *ImplantProfileQuery) All(ctx context.Context) ([]*ImplantProfile, error) {
	if err := ipq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return ipq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (ipq *ImplantProfileQuery) AllX(ctx context.Context) []*ImplantProfile {
	ips, err := ipq.All(ctx)
	if err != nil {
		panic(err)
	}
	return ips
}

// IDs executes the query and returns a list of ImplantProfile ids.
func (ipq *ImplantProfileQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := ipq.Select(implantprofile.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ipq *ImplantProfileQuery) IDsX(ctx context.Context) []int {
	ids, err := ipq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ipq *ImplantProfileQuery) Count(ctx context.Context) (int, error) {
	if err := ipq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return ipq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (ipq *ImplantProfileQuery) CountX(ctx context.Context) int {
	count, err := ipq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ipq *ImplantProfileQuery) Exist(ctx context.Context) (bool, error) {
	if err := ipq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return ipq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (ipq *ImplantProfileQuery) ExistX(ctx context.Context) bool {
	exist, err := ipq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the query builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ipq *ImplantProfileQuery) Clone() *ImplantProfileQuery {
	return &ImplantProfileQuery{
		config:     ipq.config,
		limit:      ipq.limit,
		offset:     ipq.offset,
		order:      append([]OrderFunc{}, ipq.order...),
		unique:     append([]string{}, ipq.unique...),
		predicates: append([]predicate.ImplantProfile{}, ipq.predicates...),
		// clone intermediate query.
		sql:  ipq.sql.Clone(),
		path: ipq.path,
	}
}

// GroupBy used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (ipq *ImplantProfileQuery) GroupBy(field string, fields ...string) *ImplantProfileGroupBy {
	group := &ImplantProfileGroupBy{config: ipq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := ipq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return ipq.sqlQuery(), nil
	}
	return group
}

// Select one or more fields from the given query.
func (ipq *ImplantProfileQuery) Select(field string, fields ...string) *ImplantProfileSelect {
	selector := &ImplantProfileSelect{config: ipq.config}
	selector.fields = append([]string{field}, fields...)
	selector.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := ipq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return ipq.sqlQuery(), nil
	}
	return selector
}

func (ipq *ImplantProfileQuery) prepareQuery(ctx context.Context) error {
	if ipq.path != nil {
		prev, err := ipq.path(ctx)
		if err != nil {
			return err
		}
		ipq.sql = prev
	}
	return nil
}

func (ipq *ImplantProfileQuery) sqlAll(ctx context.Context) ([]*ImplantProfile, error) {
	var (
		nodes   = []*ImplantProfile{}
		withFKs = ipq.withFKs
		_spec   = ipq.querySpec()
	)
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, implantprofile.ForeignKeys...)
	}
	_spec.ScanValues = func() []interface{} {
		node := &ImplantProfile{config: ipq.config}
		nodes = append(nodes, node)
		values := node.scanValues()
		if withFKs {
			values = append(values, node.fkValues()...)
		}
		return values
	}
	_spec.Assign = func(values ...interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(values...)
	}
	if err := sqlgraph.QueryNodes(ctx, ipq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ipq *ImplantProfileQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ipq.querySpec()
	return sqlgraph.CountNodes(ctx, ipq.driver, _spec)
}

func (ipq *ImplantProfileQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := ipq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %v", err)
	}
	return n > 0, nil
}

func (ipq *ImplantProfileQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   implantprofile.Table,
			Columns: implantprofile.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: implantprofile.FieldID,
			},
		},
		From:   ipq.sql,
		Unique: true,
	}
	if ps := ipq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ipq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ipq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ipq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ipq *ImplantProfileQuery) sqlQuery() *sql.Selector {
	builder := sql.Dialect(ipq.driver.Dialect())
	t1 := builder.Table(implantprofile.Table)
	selector := builder.Select(t1.Columns(implantprofile.Columns...)...).From(t1)
	if ipq.sql != nil {
		selector = ipq.sql
		selector.Select(selector.Columns(implantprofile.Columns...)...)
	}
	for _, p := range ipq.predicates {
		p(selector)
	}
	for _, p := range ipq.order {
		p(selector)
	}
	if offset := ipq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ipq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ImplantProfileGroupBy is the builder for group-by ImplantProfile entities.
type ImplantProfileGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ipgb *ImplantProfileGroupBy) Aggregate(fns ...AggregateFunc) *ImplantProfileGroupBy {
	ipgb.fns = append(ipgb.fns, fns...)
	return ipgb
}

// Scan applies the group-by query and scan the result into the given value.
func (ipgb *ImplantProfileGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := ipgb.path(ctx)
	if err != nil {
		return err
	}
	ipgb.sql = query
	return ipgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ipgb *ImplantProfileGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := ipgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by. It is only allowed when querying group-by with one field.
func (ipgb *ImplantProfileGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(ipgb.fields) > 1 {
		return nil, errors.New("ent: ImplantProfileGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := ipgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ipgb *ImplantProfileGroupBy) StringsX(ctx context.Context) []string {
	v, err := ipgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by. It is only allowed when querying group-by with one field.
func (ipgb *ImplantProfileGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(ipgb.fields) > 1 {
		return nil, errors.New("ent: ImplantProfileGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := ipgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ipgb *ImplantProfileGroupBy) IntsX(ctx context.Context) []int {
	v, err := ipgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by. It is only allowed when querying group-by with one field.
func (ipgb *ImplantProfileGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(ipgb.fields) > 1 {
		return nil, errors.New("ent: ImplantProfileGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := ipgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ipgb *ImplantProfileGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := ipgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by. It is only allowed when querying group-by with one field.
func (ipgb *ImplantProfileGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(ipgb.fields) > 1 {
		return nil, errors.New("ent: ImplantProfileGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := ipgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ipgb *ImplantProfileGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := ipgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ipgb *ImplantProfileGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := ipgb.sqlQuery().Query()
	if err := ipgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ipgb *ImplantProfileGroupBy) sqlQuery() *sql.Selector {
	selector := ipgb.sql
	columns := make([]string, 0, len(ipgb.fields)+len(ipgb.fns))
	columns = append(columns, ipgb.fields...)
	for _, fn := range ipgb.fns {
		columns = append(columns, fn(selector))
	}
	return selector.Select(columns...).GroupBy(ipgb.fields...)
}

// ImplantProfileSelect is the builder for select fields of ImplantProfile entities.
type ImplantProfileSelect struct {
	config
	fields []string
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Scan applies the selector query and scan the result into the given value.
func (ips *ImplantProfileSelect) Scan(ctx context.Context, v interface{}) error {
	query, err := ips.path(ctx)
	if err != nil {
		return err
	}
	ips.sql = query
	return ips.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ips *ImplantProfileSelect) ScanX(ctx context.Context, v interface{}) {
	if err := ips.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from selector. It is only allowed when selecting one field.
func (ips *ImplantProfileSelect) Strings(ctx context.Context) ([]string, error) {
	if len(ips.fields) > 1 {
		return nil, errors.New("ent: ImplantProfileSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := ips.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ips *ImplantProfileSelect) StringsX(ctx context.Context) []string {
	v, err := ips.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from selector. It is only allowed when selecting one field.
func (ips *ImplantProfileSelect) Ints(ctx context.Context) ([]int, error) {
	if len(ips.fields) > 1 {
		return nil, errors.New("ent: ImplantProfileSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := ips.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ips *ImplantProfileSelect) IntsX(ctx context.Context) []int {
	v, err := ips.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from selector. It is only allowed when selecting one field.
func (ips *ImplantProfileSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(ips.fields) > 1 {
		return nil, errors.New("ent: ImplantProfileSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := ips.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ips *ImplantProfileSelect) Float64sX(ctx context.Context) []float64 {
	v, err := ips.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from selector. It is only allowed when selecting one field.
func (ips *ImplantProfileSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(ips.fields) > 1 {
		return nil, errors.New("ent: ImplantProfileSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := ips.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ips *ImplantProfileSelect) BoolsX(ctx context.Context) []bool {
	v, err := ips.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ips *ImplantProfileSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := ips.sqlQuery().Query()
	if err := ips.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ips *ImplantProfileSelect) sqlQuery() sql.Querier {
	selector := ips.sql
	selector.Select(selector.Columns(ips.fields...)...)
	return selector
}
