// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/bishopfox/sliver/server/db/ent/implantconfig"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// ImplantConfigCreate is the builder for creating a ImplantConfig entity.
type ImplantConfigCreate struct {
	config
	mutation *ImplantConfigMutation
	hooks    []Hook
}

// Mutation returns the ImplantConfigMutation object of the builder.
func (icc *ImplantConfigCreate) Mutation() *ImplantConfigMutation {
	return icc.mutation
}

// Save creates the ImplantConfig in the database.
func (icc *ImplantConfigCreate) Save(ctx context.Context) (*ImplantConfig, error) {
	var (
		err  error
		node *ImplantConfig
	)
	if len(icc.hooks) == 0 {
		node, err = icc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ImplantConfigMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			icc.mutation = mutation
			node, err = icc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(icc.hooks) - 1; i >= 0; i-- {
			mut = icc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, icc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (icc *ImplantConfigCreate) SaveX(ctx context.Context) *ImplantConfig {
	v, err := icc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (icc *ImplantConfigCreate) sqlSave(ctx context.Context) (*ImplantConfig, error) {
	var (
		ic    = &ImplantConfig{config: icc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: implantconfig.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: implantconfig.FieldID,
			},
		}
	)
	if err := sqlgraph.CreateNode(ctx, icc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	ic.ID = int(id)
	return ic, nil
}
