// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/bishopfox/sliver/server/db/ent/implantprofile"
	"github.com/bishopfox/sliver/server/db/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// ImplantProfileDelete is the builder for deleting a ImplantProfile entity.
type ImplantProfileDelete struct {
	config
	hooks      []Hook
	mutation   *ImplantProfileMutation
	predicates []predicate.ImplantProfile
}

// Where adds a new predicate to the delete builder.
func (ipd *ImplantProfileDelete) Where(ps ...predicate.ImplantProfile) *ImplantProfileDelete {
	ipd.predicates = append(ipd.predicates, ps...)
	return ipd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ipd *ImplantProfileDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ipd.hooks) == 0 {
		affected, err = ipd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ImplantProfileMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ipd.mutation = mutation
			affected, err = ipd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ipd.hooks) - 1; i >= 0; i-- {
			mut = ipd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ipd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ipd *ImplantProfileDelete) ExecX(ctx context.Context) int {
	n, err := ipd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ipd *ImplantProfileDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: implantprofile.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: implantprofile.FieldID,
			},
		},
	}
	if ps := ipd.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, ipd.driver, _spec)
}

// ImplantProfileDeleteOne is the builder for deleting a single ImplantProfile entity.
type ImplantProfileDeleteOne struct {
	ipd *ImplantProfileDelete
}

// Exec executes the deletion query.
func (ipdo *ImplantProfileDeleteOne) Exec(ctx context.Context) error {
	n, err := ipdo.ipd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{implantprofile.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ipdo *ImplantProfileDeleteOne) ExecX(ctx context.Context) {
	ipdo.ipd.ExecX(ctx)
}
