// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/bishopfox/sliver/server/db/ent/implantconfig"
	"github.com/bishopfox/sliver/server/db/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// ImplantConfigUpdate is the builder for updating ImplantConfig entities.
type ImplantConfigUpdate struct {
	config
	hooks      []Hook
	mutation   *ImplantConfigMutation
	predicates []predicate.ImplantConfig
}

// Where adds a new predicate for the builder.
func (icu *ImplantConfigUpdate) Where(ps ...predicate.ImplantConfig) *ImplantConfigUpdate {
	icu.predicates = append(icu.predicates, ps...)
	return icu
}

// Mutation returns the ImplantConfigMutation object of the builder.
func (icu *ImplantConfigUpdate) Mutation() *ImplantConfigMutation {
	return icu.mutation
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (icu *ImplantConfigUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(icu.hooks) == 0 {
		affected, err = icu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ImplantConfigMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			icu.mutation = mutation
			affected, err = icu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(icu.hooks) - 1; i >= 0; i-- {
			mut = icu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, icu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (icu *ImplantConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := icu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (icu *ImplantConfigUpdate) Exec(ctx context.Context) error {
	_, err := icu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (icu *ImplantConfigUpdate) ExecX(ctx context.Context) {
	if err := icu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (icu *ImplantConfigUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   implantconfig.Table,
			Columns: implantconfig.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: implantconfig.FieldID,
			},
		},
	}
	if ps := icu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if n, err = sqlgraph.UpdateNodes(ctx, icu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{implantconfig.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// ImplantConfigUpdateOne is the builder for updating a single ImplantConfig entity.
type ImplantConfigUpdateOne struct {
	config
	hooks    []Hook
	mutation *ImplantConfigMutation
}

// Mutation returns the ImplantConfigMutation object of the builder.
func (icuo *ImplantConfigUpdateOne) Mutation() *ImplantConfigMutation {
	return icuo.mutation
}

// Save executes the query and returns the updated entity.
func (icuo *ImplantConfigUpdateOne) Save(ctx context.Context) (*ImplantConfig, error) {
	var (
		err  error
		node *ImplantConfig
	)
	if len(icuo.hooks) == 0 {
		node, err = icuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ImplantConfigMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			icuo.mutation = mutation
			node, err = icuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(icuo.hooks) - 1; i >= 0; i-- {
			mut = icuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, icuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (icuo *ImplantConfigUpdateOne) SaveX(ctx context.Context) *ImplantConfig {
	ic, err := icuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return ic
}

// Exec executes the query on the entity.
func (icuo *ImplantConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := icuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (icuo *ImplantConfigUpdateOne) ExecX(ctx context.Context) {
	if err := icuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (icuo *ImplantConfigUpdateOne) sqlSave(ctx context.Context) (ic *ImplantConfig, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   implantconfig.Table,
			Columns: implantconfig.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: implantconfig.FieldID,
			},
		},
	}
	id, ok := icuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing ImplantConfig.ID for update")}
	}
	_spec.Node.ID.Value = id
	ic = &ImplantConfig{config: icuo.config}
	_spec.Assign = ic.assignValues
	_spec.ScanValues = ic.scanValues()
	if err = sqlgraph.UpdateNode(ctx, icuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{implantconfig.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return ic, nil
}
