// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// ImplantsColumns holds the columns for the "implants" table.
	ImplantsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "id", Type: field.TypeUUID},
		{Name: "goos", Type: field.TypeString},
		{Name: "goarch", Type: field.TypeString},
		{Name: "ecc_client_cert", Type: field.TypeString},
		{Name: "ecc_client_key", Type: field.TypeString},
		{Name: "rsa_cert", Type: field.TypeString},
		{Name: "debug", Type: field.TypeBool},
		{Name: "obfuscate_symbols", Type: field.TypeBool},
		{Name: "reconnect_interval", Type: field.TypeUint32},
		{Name: "max_connection_errors", Type: field.TypeUint32},
		{Name: "limit_domain_joined", Type: field.TypeBool},
		{Name: "limit_datetime", Type: field.TypeInt64},
		{Name: "limit_hostname", Type: field.TypeString},
		{Name: "limit_username", Type: field.TypeString},
		{Name: "output_format", Type: field.TypeInt},
	}
	// ImplantsTable holds the schema information for the "implants" table.
	ImplantsTable = &schema.Table{
		Name:        "implants",
		Columns:     ImplantsColumns,
		PrimaryKey:  []*schema.Column{ImplantsColumns[0], ImplantsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ImplantsTable,
	}
)

func init() {
}
