// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// BuildTasksColumns holds the columns for the "build_tasks" table.
	BuildTasksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "guid", Type: field.TypeUUID},
	}
	// BuildTasksTable holds the schema information for the "build_tasks" table.
	BuildTasksTable = &schema.Table{
		Name:        "build_tasks",
		Columns:     BuildTasksColumns,
		PrimaryKey:  []*schema.Column{BuildTasksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// ImplantConfigsColumns holds the columns for the "implant_configs" table.
	ImplantConfigsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// ImplantConfigsTable holds the schema information for the "implant_configs" table.
	ImplantConfigsTable = &schema.Table{
		Name:        "implant_configs",
		Columns:     ImplantConfigsColumns,
		PrimaryKey:  []*schema.Column{ImplantConfigsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// ImplantProfilesColumns holds the columns for the "implant_profiles" table.
	ImplantProfilesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// ImplantProfilesTable holds the schema information for the "implant_profiles" table.
	ImplantProfilesTable = &schema.Table{
		Name:        "implant_profiles",
		Columns:     ImplantProfilesColumns,
		PrimaryKey:  []*schema.Column{ImplantProfilesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BuildTasksTable,
		ImplantConfigsTable,
		ImplantProfilesTable,
	}
)

func init() {
}
