// Code generated by entc, DO NOT EDIT.

package implantconfig

const (
	// Label holds the string label denoting the implantconfig type in the database.
	Label = "implant_config"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"

	// Table holds the table name of the implantconfig in the database.
	Table = "implant_configs"
)

// Columns holds all SQL columns for implantconfig fields.
var Columns = []string{
	FieldID,
}
