// Code generated by entc, DO NOT EDIT.

package buildtask

const (
	// Label holds the string label denoting the buildtask type in the database.
	Label = "build_task"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStarted holds the string denoting the started field in the database.
	FieldStarted = "started"
	// FieldCompleted holds the string denoting the completed field in the database.
	FieldCompleted = "completed"

	// EdgeImplant holds the string denoting the implant edge name in mutations.
	EdgeImplant = "Implant"
	// EdgeImplantProfile holds the string denoting the implantprofile edge name in mutations.
	EdgeImplantProfile = "ImplantProfile"

	// Table holds the table name of the buildtask in the database.
	Table = "build_tasks"
	// ImplantTable is the table the holds the Implant relation/edge.
	ImplantTable = "implants"
	// ImplantInverseTable is the table name for the Implant entity.
	// It exists in this package in order to avoid circular dependency with the "implant" package.
	ImplantInverseTable = "implants"
	// ImplantColumn is the table column denoting the Implant relation/edge.
	ImplantColumn = "build_task_implant"
	// ImplantProfileTable is the table the holds the ImplantProfile relation/edge.
	ImplantProfileTable = "implant_profiles"
	// ImplantProfileInverseTable is the table name for the ImplantProfile entity.
	// It exists in this package in order to avoid circular dependency with the "implantprofile" package.
	ImplantProfileInverseTable = "implant_profiles"
	// ImplantProfileColumn is the table column denoting the ImplantProfile relation/edge.
	ImplantProfileColumn = "build_task_implant_profile"
)

// Columns holds all SQL columns for buildtask fields.
var Columns = []string{
	FieldID,
	FieldStarted,
	FieldCompleted,
}
