// Code generated by entc, DO NOT EDIT.

package buildtask

const (
	// Label holds the string label denoting the buildtask type in the database.
	Label = "build_task"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldGUID holds the string denoting the guid field in the database.
	FieldGUID = "guid"

	// Table holds the table name of the buildtask in the database.
	Table = "build_tasks"
)

// Columns holds all SQL columns for buildtask fields.
var Columns = []string{
	FieldID,
	FieldGUID,
}
