// Code generated by entc, DO NOT EDIT.

package implantprofile

const (
	// Label holds the string label denoting the implantprofile type in the database.
	Label = "implant_profile"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"

	// Table holds the table name of the implantprofile in the database.
	Table = "implant_profiles"
)

// Columns holds all SQL columns for implantprofile fields.
var Columns = []string{
	FieldID,
}
